apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nexus-repo1.carbon-k8s.online/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: demo
      imagePullSecrets:
        - name: nexus-repo

---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-repo
type: Opaque
data:
  username: YWRtaW4=
  password: TiFAI2V4dXM5
