apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nexus-repo1.carbon-k8s.online/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: demo
      imagePullSecrets:
        - name: nexus-repo

---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy1yZXBvMS5jYXJib24tazhzLm9ubGluZSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJOIUAjZXh1czkiLCJhdXRoIjoiWVdSdGFXNDZUaUZBSTJWNGRYTTUifX19
metadata:
  creationTimestamp: null
  name: nexes-repo
type: kubernetes.io/dockerconfigjson
